### ISSUE TITLE
As a follower and fan of yours, can you please help?

### ISSUE THREAD

**Issue by Isonomic** [davefaliskie/travel_budget#1]
This happens on this screen. I think it needs a single child scroll view, but cant figure out where to even put it as the page is broken up into tiny pieces. Can you please help a guy out?
![Screenshot (138)](https://user-images.githubusercontent.com/37713396/69381115-3fd54280-0c71-11ea-91f2-71d810d2b44c.png)

**Comment by davefaliskie** [comment]
Yes, a single child scroll view will fix this. Typically when you want the whole page to be scrollable you want your SingleChildScrollView to be the first widget under your scaffold. Since the sign up view actually has two potential scaffolds (sign up and sign in) there are two places to add it. I made the changes in this commit. https://github.com/davefaliskie/travel_budget/commit/25062ab700b8589bf823c2545b5140092fadeda1
